"""Pre-build hook: 把 config/protocol.json 渲染成 include/protocol_config.h.

通过 platformio.ini 的 extra_scripts 钩子注入构建流程:
    extra_scripts = pre:scripts/gen_protocol_config.py

设计要点:
  1) 真实协议描述符 (protocol.json) 是 gitignored 的, 仅本地保存.
  2) 公开仓库会带一份 protocol.example.json 作为占位; 当真实文件缺失时
     自动 fallback 到 example, 让首次 clone 的用户也能编译通过.
  3) 生成的 protocol_config.h 同样不入库, 完全由本脚本管理.
  4) 仅在内容发生变化时才覆盖输出文件, 避免不必要的全量重编.
"""

import json
import os
import sys

# -----------------------------------------------------------------------------
# 路径解析
# -----------------------------------------------------------------------------
# 脚本既可能被 PlatformIO 通过 SCons 的 Import("env") 上下文注入运行,
# 也可能被开发者直接 `python3 gen_protocol_config.py` 单独执行.
# 两种情况下都需要拿到 PROJECT_DIR (即 Software/ 根目录).
try:  # pragma: no cover - PlatformIO context
    Import("env")  # type: ignore  # noqa: F821
    _PIO_ENV = env  # type: ignore  # noqa: F821
    PROJECT_DIR = _PIO_ENV["PROJECT_DIR"]
except NameError:  # pragma: no cover - standalone context
    # 脚本位于 Software/scripts/, 上跳两级即得 Software/
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CONFIG_DIR   = os.path.join(PROJECT_DIR, "config")
REAL_PATH    = os.path.join(CONFIG_DIR, "protocol.json")
EXAMPLE_PATH = os.path.join(CONFIG_DIR, "protocol.example.json")
OUT_PATH     = os.path.join(PROJECT_DIR, "include", "protocol_config.h")


def parse_int(value):
    """把 JSON 字段解析为 Python int.

    支持三种输入:
      - int   : 直接返回
      - str   : 同时支持十进制 ("123") 与十六进制 ("0xFF" / "0xff")
      - bool  : 显式拒绝, 防止 True/False 被悄悄当作 1/0

    其它类型 (list / None / float) 一律抛 TypeError, 便于在 JSON 编辑出错时
    在构建期立刻发现, 而不是带病编译.
    """
    if isinstance(value, bool):
        raise TypeError("bool is not a valid int field")
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        text = value.strip()
        if text.lower().startswith("0x"):
            return int(text, 16)
        return int(text)
    raise TypeError("Cannot parse {!r} as int".format(value))


def snake_to_camel(name):
    """snake_case -> CamelCase, 用于命令名拼接成 C++ 常量名.

    例: "tx_record_start" -> "TxRecordStart", 最终拼成 "kCmdTxRecordStart".
    """
    return "".join(p.capitalize() for p in name.split("_") if p)


def render_protocol_header(cfg):
    """把解析后的 JSON dict 渲染为 C++ 头内容字符串.

    流程:
      1) 取出 4 个顶层节: ble / frame / qc / modes
      2) 解析两个 3 字节帧头, 校验长度
      3) 解析 modes.switch_sequence, 不允许为空
      4) 逐段拼装 C++ 常量声明:
         - BLE GATT 参数 (GAP 名 / 3 个 UUID16 / MTU)
         - 帧布局 (头长 / max_data / END 位 / token payload 长 / 出向头 / 入向头)
         - 命令字 (按 _ 分隔的下划线名 -> CamelCase 拼成 kCmd 前缀)
         - QC 广播 (rotate_period_ms / prefix[] / token_length / suffix[])
         - 模式切换序列 (数组 + 长度)
      5) 返回完整 C++ 头文件字符串

    注意: 命令字会跳过以下划线开头的 "_doc" 这类元字段.
    """
    ble    = cfg["ble"]
    frame  = cfg["frame"]
    qc     = cfg["qc"]
    modes  = cfg["modes"]

    head_out = [parse_int(x) for x in frame["head_outbound"]]
    head_in  = [parse_int(x) for x in frame["head_inbound"]]
    if len(head_out) != 3 or len(head_in) != 3:
        raise ValueError("frame.head_* must be 3 bytes")

    cmds = frame["commands"]
    seq  = [parse_int(x) for x in modes["switch_sequence"]]
    if not seq:
        raise ValueError("modes.switch_sequence must not be empty")

    out = []
    # ---- 文件头声明: 警告手工修改 ----
    out.append("// AUTO-GENERATED by Software/scripts/gen_protocol_config.py")
    out.append("// Source : config/protocol.json (or config/protocol.example.json)")
    out.append("// DO NOT EDIT BY HAND - your changes will be overwritten on next build.")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("namespace cw {")
    out.append("namespace ble {")
    out.append("namespace cfg {")
    out.append("")

    # ---- BLE GATT 参数 ----
    out.append("// ===== BLE GATT server parameters =====")
    out.append('constexpr const char* kRemoteGapName       = "{}";'
               .format(ble["gap_name"]))
    out.append("constexpr uint16_t   kRemoteServiceUuid16 = 0x{:04X};"
               .format(parse_int(ble["service_uuid16"])))
    out.append("constexpr uint16_t   kRemoteWriteUuid16   = 0x{:04X};"
               .format(parse_int(ble["write_char_uuid16"])))
    out.append("constexpr uint16_t   kRemoteNotifyUuid16  = 0x{:04X};"
               .format(parse_int(ble["notify_char_uuid16"])))
    out.append("constexpr uint16_t   kPreferredMtu        = {};"
               .format(parse_int(ble["preferred_mtu"])))
    out.append("")

    # ---- 帧布局 ----
    out.append("// ===== Frame layout =====")
    out.append("constexpr uint8_t kFrameHeadLen            = {};"
               .format(parse_int(frame["head_length"])))
    out.append("constexpr uint8_t kFrameMaxData            = {};"
               .format(parse_int(frame["max_data_len"])))
    out.append("constexpr uint8_t kFrameEndBit             = 0x{:02X};"
               .format(parse_int(frame["end_bit"])))
    out.append("constexpr uint8_t kFramePeerTokenPayloadLen = {};"
               .format(parse_int(frame["peer_token_payload_length"])))
    out.append("constexpr uint8_t kFrameHeadOutbound[3]    = {{ 0x{:02X}, 0x{:02X}, 0x{:02X} }};"
               .format(head_out[0], head_out[1], head_out[2]))
    out.append("constexpr uint8_t kFrameHeadInbound[3]     = {{ 0x{:02X}, 0x{:02X}, 0x{:02X} }};"
               .format(head_in[0], head_in[1], head_in[2]))
    out.append("")

    # ---- 命令字 ----
    out.append("// ===== Command bytes =====")
    for name, value in cmds.items():
        # 跳过 _doc 等元字段
        if name.startswith("_"):
            continue
        c_name = "kCmd" + snake_to_camel(name)
        out.append("constexpr uint8_t {:<32}= 0x{:02X};"
                   .format(c_name, parse_int(value)))
    out.append("")

    # ---- QC 广播 ----
    # manufacturer-data 模板拆为 prefix / token / suffix 三段
    mfr     = qc["manufacturer_data"]
    prefix  = [parse_int(x) for x in mfr["prefix"]]
    suffix  = [parse_int(x) for x in mfr["suffix"]]
    tok_len = parse_int(mfr["token_length"])
    rot_ms  = parse_int(qc["rotate_period_ms"])
    if not prefix:
        raise ValueError("qc.manufacturer_data.prefix must not be empty")
    if rot_ms <= 0:
        raise ValueError("qc.rotate_period_ms must be > 0")

    out.append("// ===== QC (Quick Capture) advertisement =====")
    out.append("// 已配对状态下与普通广播轮流交替, 每 kQcAdvRotatePeriodMs 切换一次")
    out.append("constexpr uint32_t kQcAdvRotatePeriodMs = {};"
               .format(rot_ms))
    out.append("// manufacturer-data 字节布局: [prefix N][token M][suffix P]")
    out.append("// prefix 已包含 CompanyID 2B (LE)")
    out.append("constexpr uint8_t  kQcTokenLen      = {};".format(tok_len))
    out.append("constexpr uint8_t  kQcAdvPrefix[]   = {{ {} }};"
               .format(", ".join("0x{:02X}".format(b) for b in prefix)))
    out.append("constexpr uint8_t  kQcAdvPrefixLen  = {};".format(len(prefix)))
    out.append("constexpr uint8_t  kQcAdvSuffix[]   = {{ {} }};"
               .format(", ".join("0x{:02X}".format(b) for b in suffix)))
    out.append("constexpr uint8_t  kQcAdvSuffixLen  = {};".format(len(suffix)))
    out.append("")

    # ---- 模式切换序列 ----
    out.append("// ===== Mode-switch sequence (cycled on each tx_set_mode) =====")
    out.append("constexpr uint8_t kModeSwitchSeq[]         = {{ {} }};"
               .format(", ".join(str(v) for v in seq)))
    out.append("constexpr uint8_t kModeSwitchSeqLen        = {};"
               .format(len(seq)))
    out.append("")

    out.append("}  // namespace cfg")
    out.append("}  // namespace ble")
    out.append("}  // namespace cw")
    out.append("")
    return "\n".join(out)


def main():
    """脚本主入口.

    流程:
      1) 选择源文件:
         - 优先用 config/protocol.json (真实协议)
         - 不存在则 fallback 到 config/protocol.example.json (占位)
         - 都不存在则 stderr 报错并退出 (返回码 1)
      2) 读取 JSON
      3) 调用 render() 产出 C++ 头内容
      4) 创建输出目录 (include/) 如不存在
      5) 增量写入: 与现有文件比对, 只有内容变化时才重写文件
         避免触发不必要的全量重编
      6) 打印一行简明状态, 让构建日志便于排查
    """
    if os.path.isfile(REAL_PATH):
        src = REAL_PATH
        tag = "real"
    elif os.path.isfile(EXAMPLE_PATH):
        src = EXAMPLE_PATH
        tag = "EXAMPLE (placeholder)"
        print("[gen_protocol_config] WARNING: {} not found, using example values"
              .format(REAL_PATH))
    else:
        sys.stderr.write("[gen_protocol_config] ERROR: neither {} nor {} exist\n"
                         .format(REAL_PATH, EXAMPLE_PATH))
        sys.exit(1)

    with open(src, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    content = render_protocol_header(cfg)
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)

    # 增量写入: 内容未变则不动文件, 让 SCons 不会重编依赖
    if os.path.isfile(OUT_PATH):
        with open(OUT_PATH, "r", encoding="utf-8") as f:
            existing = f.read()
        if existing == content:
            print("[gen_protocol_config] up-to-date ({})".format(tag))
            return

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    print("[gen_protocol_config] generated {} from {}".format(OUT_PATH, tag))


main()
