from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

cyberwand_circuit = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'ESP32-S3-WROOM-1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESP32-S3-WROOM-1'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'RF_Module:ESP32-S3-WROOM-1', 'keywords':None, 'description':'ESP32-S3 Module with 16MB Flash + 8MB PSRAM', 'datasheet':None, 'pins':[
            Pin(num='1',name='GND1',func=pin_types.PWRIN),
            Pin(num='2',name='3V3',func=pin_types.PWRIN),
            Pin(num='3',name='EN',func=pin_types.INPUT),
            Pin(num='40',name='GND2',func=pin_types.PWRIN),
            Pin(num='41',name='EPAD',func=pin_types.PWRIN),
            Pin(num='4',name='IO4',func=pin_types.BIDIR),
            Pin(num='5',name='IO5',func=pin_types.BIDIR),
            Pin(num='6',name='IO6',func=pin_types.BIDIR),
            Pin(num='7',name='IO7',func=pin_types.BIDIR),
            Pin(num='8',name='IO15',func=pin_types.BIDIR),
            Pin(num='9',name='IO16',func=pin_types.BIDIR),
            Pin(num='10',name='IO17',func=pin_types.BIDIR),
            Pin(num='11',name='IO18',func=pin_types.BIDIR),
            Pin(num='12',name='IO8',func=pin_types.BIDIR),
            Pin(num='13',name='IO19',func=pin_types.BIDIR),
            Pin(num='14',name='IO20',func=pin_types.BIDIR),
            Pin(num='15',name='IO3',func=pin_types.BIDIR),
            Pin(num='16',name='IO46',func=pin_types.INPUT),
            Pin(num='17',name='IO9',func=pin_types.BIDIR),
            Pin(num='18',name='IO10',func=pin_types.BIDIR),
            Pin(num='19',name='IO11',func=pin_types.BIDIR),
            Pin(num='20',name='IO12',func=pin_types.BIDIR),
            Pin(num='21',name='IO13',func=pin_types.BIDIR),
            Pin(num='22',name='IO14',func=pin_types.BIDIR),
            Pin(num='23',name='IO21',func=pin_types.BIDIR),
            Pin(num='24',name='IO47',func=pin_types.BIDIR),
            Pin(num='25',name='IO48',func=pin_types.BIDIR),
            Pin(num='26',name='IO45',func=pin_types.BIDIR),
            Pin(num='27',name='IO0',func=pin_types.BIDIR),
            Pin(num='28',name='IO35_PSRAM',func=pin_types.NOCONNECT),
            Pin(num='29',name='IO36_PSRAM',func=pin_types.NOCONNECT),
            Pin(num='30',name='IO37_PSRAM',func=pin_types.NOCONNECT),
            Pin(num='31',name='IO38',func=pin_types.BIDIR),
            Pin(num='32',name='IO39',func=pin_types.BIDIR),
            Pin(num='33',name='IO40',func=pin_types.BIDIR),
            Pin(num='34',name='IO41',func=pin_types.BIDIR),
            Pin(num='35',name='IO42',func=pin_types.BIDIR),
            Pin(num='36',name='RXD0',func=pin_types.BIDIR),
            Pin(num='37',name='TXD0',func=pin_types.BIDIR),
            Pin(num='38',name='IO2',func=pin_types.BIDIR),
            Pin(num='39',name='IO1',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'MPU-6050', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MPU-6050'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Sensor_Motion:InvenSense_QFN-24_4x4mm_P0.5mm', 'keywords':None, 'description':'MPU6050 6-axis IMU, QFN-24', 'datasheet':None, 'pins':[
            Pin(num='13',name='VDD',func=pin_types.PWRIN),
            Pin(num='18',name='GND',func=pin_types.PWRIN),
            Pin(num='8',name='VLOGIC',func=pin_types.PWRIN),
            Pin(num='24',name='SDA',func=pin_types.BIDIR),
            Pin(num='23',name='SCL',func=pin_types.INPUT),
            Pin(num='9',name='AD0',func=pin_types.INPUT),
            Pin(num='12',name='INT',func=pin_types.OUTPUT),
            Pin(num='6',name='AUX_DA',func=pin_types.BIDIR),
            Pin(num='7',name='AUX_CL',func=pin_types.BIDIR),
            Pin(num='1',name='CLKIN',func=pin_types.INPUT),
            Pin(num='11',name='FSYNC',func=pin_types.INPUT),
            Pin(num='20',name='CPOUT',func=pin_types.PASSIVE),
            Pin(num='10',name='REGOUT',func=pin_types.PASSIVE),
            Pin(num='19',name='RESV',func=pin_types.NOCONNECT)] }),
        Part(**{ 'name':'HS20S010B_LCD', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'HS20S010B_LCD'}), 'ref_prefix':'LCD', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x10_P2.54mm_Vertical', 'keywords':None, 'description':'HS20S010B 2.0 inch TFT LCD, 240x320, ST7789V2 driver, GT30L32S4W font IC', 'datasheet':None, 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='VCC',func=pin_types.PWRIN),
            Pin(num='3',name='SCL',func=pin_types.INPUT),
            Pin(num='4',name='SDA',func=pin_types.BIDIR),
            Pin(num='5',name='RES',func=pin_types.INPUT),
            Pin(num='6',name='DC',func=pin_types.INPUT),
            Pin(num='7',name='CS',func=pin_types.INPUT),
            Pin(num='8',name='BLK',func=pin_types.INPUT),
            Pin(num='9',name='FSO',func=pin_types.OUTPUT),
            Pin(num='10',name='FCS',func=pin_types.INPUT)] }),
        Part(**{ 'name':'MicroSD_Socket', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MicroSD_Socket'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_Card:microSD_HC_Hirose_DM3AT-SF-PEJM5', 'keywords':None, 'description':'MicroSD Socket with SPI', 'datasheet':None, 'pins':[
            Pin(num='4',name='VCC',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='CS',func=pin_types.INPUT),
            Pin(num='5',name='SCK',func=pin_types.INPUT),
            Pin(num='7',name='MOSI',func=pin_types.INPUT),
            Pin(num='8',name='MISO',func=pin_types.TRISTATE),
            Pin(num='9',name='CD',func=pin_types.PASSIVE),
            Pin(num='1',name='SHIELD',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'DFPlayer_Mini', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DFPlayer_Mini'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_2x08_P2.54mm_Vertical', 'keywords':None, 'description':'DFPlayer Mini MP3 Module', 'datasheet':None, 'pins':[
            Pin(num='1',name='VCC',func=pin_types.PWRIN),
            Pin(num='7',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='RX',func=pin_types.INPUT),
            Pin(num='3',name='TX',func=pin_types.OUTPUT),
            Pin(num='16',name='BUSY',func=pin_types.OUTPUT),
            Pin(num='8',name='SPK1',func=pin_types.OUTPUT),
            Pin(num='9',name='SPK2',func=pin_types.OUTPUT),
            Pin(num='4',name='DAC_R',func=pin_types.OUTPUT),
            Pin(num='5',name='DAC_L',func=pin_types.OUTPUT),
            Pin(num='11',name='IO1',func=pin_types.BIDIR),
            Pin(num='12',name='IO2',func=pin_types.BIDIR),
            Pin(num='13',name='ADKEY1',func=pin_types.INPUT),
            Pin(num='14',name='ADKEY2',func=pin_types.INPUT),
            Pin(num='15',name='USB_P',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'INMP441', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'INMP441'}), 'ref_prefix':'MIC', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical', 'keywords':None, 'description':'INMP441 MEMS Microphone Module', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SCK',func=pin_types.INPUT),
            Pin(num='4',name='SD',func=pin_types.OUTPUT),
            Pin(num='5',name='WS',func=pin_types.INPUT),
            Pin(num='6',name='L_R',func=pin_types.INPUT)] }),
        Part(**{ 'name':'WS2812B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'WS2812B'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'LED_SMD:LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm', 'keywords':None, 'description':'WS2812B RGB LED', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='DIN',func=pin_types.INPUT),
            Pin(num='2',name='DOUT',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'USB_C_Receptacle_USB2.0', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_C_Receptacle_USB2.0'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_USB:USB_C_Receptacle_HRO_TYPE-C-31-M-12', 'keywords':None, 'description':'USB Type-C Receptacle', 'datasheet':None, 'pins':[
            Pin(num='A4',name='VBUS_A4',func=pin_types.PWRIN),
            Pin(num='B4',name='VBUS_B4',func=pin_types.PWRIN),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR),
            Pin(num='A6',name='DP1',func=pin_types.BIDIR),
            Pin(num='A7',name='DN1',func=pin_types.BIDIR),
            Pin(num='B6',name='DP2',func=pin_types.BIDIR),
            Pin(num='B7',name='DN2',func=pin_types.BIDIR),
            Pin(num='A8',name='SBU1',func=pin_types.BIDIR),
            Pin(num='B8',name='SBU2',func=pin_types.BIDIR),
            Pin(num='A1',name='GND_A1',func=pin_types.PWRIN),
            Pin(num='B1',name='GND_B1',func=pin_types.PWRIN),
            Pin(num='A12',name='GND_A12',func=pin_types.PWRIN),
            Pin(num='B12',name='GND_B12',func=pin_types.PWRIN),
            Pin(num='S1',name='SHIELD',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'Battery_Cell', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Battery_Cell'}), 'ref_prefix':'BT', 'fplist':None, 'footprint':'Connector_JST:JST_PH_S2B-PH-K_1x02_P2.00mm_Horizontal', 'keywords':None, 'description':'603040 Li-Po Battery 800mAh with JST connector', 'datasheet':None, 'pins':[
            Pin(num='1',name='+',func=pin_types.PASSIVE),
            Pin(num='2',name='-',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'TP4056', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TP4056'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'keywords':None, 'description':'TP4056 Li-Ion Charger, SOIC-8', 'datasheet':None, 'pins':[
            Pin(num='1',name='TEMP',func=pin_types.INPUT),
            Pin(num='2',name='PROG',func=pin_types.PASSIVE),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='VCC',func=pin_types.PWRIN),
            Pin(num='5',name='BAT',func=pin_types.PWROUT),
            Pin(num='6',name='STDBY',func=pin_types.OPENCOLL),
            Pin(num='7',name='CHRG',func=pin_types.OPENCOLL),
            Pin(num='8',name='CE',func=pin_types.INPUT)] }),
        Part(**{ 'name':'ME6211A33', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ME6211A33'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':None, 'description':'ME6211 3.3V/500mA LDO, SOT-23-3', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN),
            Pin(num='2',name='VOUT',func=pin_types.PWROUT),
            Pin(num='3',name='VSS',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'USBLC6-2SC6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USBLC6-2SC6'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':None, 'description':'USB ESD Protection, SOT-23-6, 0.4pF, IEC61000-4-2 Level 4', 'datasheet':None, 'pins':[
            Pin(num='1',name='IO1_1',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='IO2_1',func=pin_types.PASSIVE),
            Pin(num='4',name='IO2_2',func=pin_types.PASSIVE),
            Pin(num='5',name='VBUS',func=pin_types.PWRIN),
            Pin(num='6',name='IO1_2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'PTC_Fuse', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PTC_Fuse'}), 'ref_prefix':'F', 'fplist':None, 'footprint':'Fuse:Fuse_1206_3216Metric', 'keywords':None, 'description':'PTC Resettable Fuse 750mA/13.2V, 1206', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SN74AHCT125', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SN74AHCT125'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-14_3.9x8.7mm_P1.27mm', 'keywords':None, 'description':'74AHCT125 Quad Level-Shifter 3.3V to 5V, SOIC-14', 'datasheet':None, 'pins':[
            Pin(num='14',name='VCC',func=pin_types.PWRIN),
            Pin(num='7',name='GND',func=pin_types.PWRIN),
            Pin(num='1',name='1OE',func=pin_types.INPUT),
            Pin(num='2',name='1A',func=pin_types.INPUT),
            Pin(num='3',name='1Y',func=pin_types.OUTPUT),
            Pin(num='4',name='2OE',func=pin_types.INPUT),
            Pin(num='5',name='2A',func=pin_types.INPUT),
            Pin(num='6',name='2Y',func=pin_types.OUTPUT),
            Pin(num='9',name='3OE',func=pin_types.INPUT),
            Pin(num='8',name='3A',func=pin_types.INPUT),
            Pin(num='10',name='3Y',func=pin_types.OUTPUT),
            Pin(num='12',name='4OE',func=pin_types.INPUT),
            Pin(num='11',name='4A',func=pin_types.INPUT),
            Pin(num='13',name='4Y',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'SW_SPDT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SW_SPDT'}), 'ref_prefix':'SW', 'fplist':None, 'footprint':'Button_Switch_SMD:SW_SPDT_Shouhan_MSK12C02', 'keywords':None, 'description':'SPDT Slide Switch for Power Control', 'datasheet':None, 'pins':[
            Pin(num='1',name='COM',func=pin_types.PASSIVE),
            Pin(num='2',name='NO',func=pin_types.PASSIVE),
            Pin(num='3',name='NC',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SW_Push', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SW_Push'}), 'ref_prefix':'SW', 'fplist':None, 'footprint':'Button_Switch_SMD:SW_SPST_TL3342', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'Speaker', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Speaker'}), 'ref_prefix':'LS', 'fplist':None, 'footprint':'TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-1,5-2_1x02_P5.00mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'LED_SMD:LED_0805_2012Metric', 'keywords':None, 'description':'Red LED', 'datasheet':None, 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE),
            Pin(num='2',name='K',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] })])